### ISSUE TITLE
AssertionError in converting Googlenet

### ISSUE THREAD

**Issue by midiareshadi** [Accelergy-Project/pytorch2timeloop-converter#2]
I get the following error in converting Googlenet:

> File "/home/pytorch2timeloop-converter/pytorch2timeloop/converter_pytorch.py", line 252, in extract_layer_data
>     "Different number of conv layers detected by filter and io"
> AssertionError: Different number of conv layers detected by filter and io

The converter file includes the following parameters: 
```
import torchvision.models as models
import pytorch2timeloop
net = models.googlenet()
input_shape = (3, 224, 224)
batch_size = 1
top_dir = 'workloads'
sub_dir = 'googlenet'
convert_fc = True
exception_module_names = []
pytorch2timeloop.convert_model(net, input_shape, batch_size, sub_dir, top_dir, convert_fc, exception_module_names)
```

**Comment by nellie-wu** [comment]
This error is because the inference architecture and training architecture are different for GoogleNet. More specifically, there are several "auxiliary" modules used only for training. Since the converter only extracts modules in inference mode, the misalignment causes this assertion. 

To avoid this error, please set the `exception_module_names` to include the auxiliary modules, so that the converter will extract the modules for inference with no misalignment. More specifically, `exception_module_names = [ "aux" ]` will solve the issue.
